baseURL = "https://tansawit.me"
title   = "Sawit Trisirisatayawong"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"



PygmentsCodeFences = true
PygmentsStyle = "nord"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-148434389-1"
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

  [author]
  name = "Sawit Trisirisatayawong"

[blackfriday]
  hrefTargetBlank = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Sawit Trisirisatayawong"
  keywords = "homepage, blog, science, computer, development, programming, projects"
  images = [""]

  homeSubtitle = "Software Engineer. Data Science and Machine Learning Enthusiast. @tansawit on most places"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  [taxonomies]
    tag      = "tags"
    category = "categories"

  [params.logo]
    logoText     = "tansawit"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/tansawit"

  [[params.social]]
    name = "github"
    url  = "https://github.com/tansawit"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/tansawit"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/tansawit"

  [[params.social]]
    name = "email"
    url  = "mailto:sawit.tr@gmail.com"


[languages]
  [languages.en]
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
[menu]
  [[menu.main]]
    identifier = "home"
    weight     = 1
    name       = "Home"
    url        = "/"
  [[menu.main]]
    identifier = "about"
    weight     = 2
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "projects"
    weight     = 3
    name       = "Projects"
    url        = "projects/"
  [[menu.main]]
    identifier = "blog"
    weight     = 4
    name       = "Blog"
    url        = "posts/"
  [[menu.main]]
    identifier = "secondbrain"
    weight     = 5
    name       = "Brain"
    url        = "https://notes.tansawit.me/" 
  [[menu.main]]
    name       = "Likes"
    weight     = 6
    identifier = "likes"
    url        = "likes/"
  [[menu.main]]
    name       = "Resume"
    identifier = "resume"
    weight     = 0
    url        = "sawit-trisirisatayawong-resume.pdf"
